wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/fun_run.py
    python_version: 3.10.11
    cli_version: 0.15.9.dev1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693954730.487755
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.10.11
      5: 0.15.9.dev1
      8:
      - 4
      - 5
