wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/fun_run.py
    python_version: 3.11.4
    cli_version: 0.15.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693955014.115415
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.11.4
      5: 0.15.8
      8:
      - 4
      - 5
